version: "3.8"

services:
  api:
    image: 505999908978.dkr.ecr.eu-north-1.amazonaws.com/todo-app:latest
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: MyS3cur3P@ss
      DB_NAME: todo_db
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: MyS3cur3P@ss
      MYSQL_DATABASE: todo_db
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

volumes:
  db_data: